### ISSUE TITLE
Google Console button

### ISSUE THREAD

**Issue by Code-Neptune** [googlecodelabs/user-authentication-with-iap#1]
There is instruction on codelab "In the upper left-hand part of the lab page, click the Open Google Console button". I didn't find it.

**Comment by APratham** [comment]
I am not sure what you mean. If you are attempting the codelab through Google Codelabs/Qwiklabs, you should have been able to locate the "Open Google Console" button, considering you have started the lab first. 

Do let me know if anything else is required. If I solved your question, please close this issue
